[package]
name = "num"
version = "0.1.0"
authors = ["Nathan Faucett <nathanfaucett@gmail.com>"]

keywords = ["num", "number", "float", "int"]
description = "generic number trait"
license = "MIT"
readme = "README.md"
repository = "https://github.com/nathanfaucett/rs-num.git"
homepage = "https://github.com/nathanfaucett/rs-num"

[dependencies]
libc = "0.2.9"
